plugins {
    id 'java'
}

group = 'com.mrpotato'
version = '1.20.5-3.0-pre-release-1'
description = 'Simplifies Commands'
java.sourceCompatibility = JavaVersion.VERSION_21

repositories {
    mavenCentral()
    maven { url 'https://repo.papermc.io/repository/maven-public/' }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.20.6-R0.1-SNAPSHOT'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

jar {
    from('.') {
        include 'plugin.yml'
    }
}

